import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://rahulshettyacademy.com/client/#/auth/login');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'email@example.com' }).click();
  await page.getByRole('textbox', { name: 'email@example.com' }).fill('alapati.ramya@ymail.com');
  await page.getByRole('textbox', { name: 'email@example.com' }).press('Tab');
  await page.getByRole('textbox', { name: 'enter your passsword' }).fill('Ramya!987');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('Register here').click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('asasasas');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('asasasasa');
  await page.getByRole('textbox', { name: 'Last Name' }).fill('sasasaas');
  await page.getByRole('textbox', { name: 'email@example.com' }).click();
  await page.getByRole('textbox', { name: 'email@example.com' }).fill('asasasa');
  await page.getByRole('textbox', { name: 'enter your number' }).click();
  await page.getByRole('textbox', { name: 'enter your number' }).fill('aaaasas');
  await page.getByRole('combobox').selectOption('3: Engineer');
  await page.getByRole('radio', { name: 'Male', exact: true }).check();
  await page.getByRole('radio', { name: 'Male', exact: true }).press('s');
  await page.getByRole('textbox', { name: 'Passsword' }).click();
  await page.getByRole('radio', { name: 'Male', exact: true }).press('a');
  await page.getByRole('radio', { name: 'Male', exact: true }).press('s');
  await page.getByRole('radio', { name: 'Male', exact: true }).press('a');
  await page.getByRole('radio', { name: 'Male', exact: true }).press('s');
  await page.getByRole('radio', { name: 'Male', exact: true }).press('a');
  await page.getByRole('radio', { name: 'Male', exact: true }).press('s');
  await page.getByRole('radio', { name: 'Male', exact: true }).press('a');
  await page.getByRole('textbox', { name: 'Passsword' }).click();
  await page.getByRole('textbox', { name: 'Passsword' }).fill('as');
  await page.getByRole('textbox', { name: 'Passsword' }).click();
  await page.getByRole('textbox', { name: 'Passsword' }).fill('asasasasasasa');
  await page.getByRole('textbox', { name: 'Confirm Password' }).click();
  await page.getByRole('textbox', { name: 'Confirm Password' }).fill('aaadadadd');
  await page.getByRole('checkbox').check();
});